### ISSUE TITLE
Integrate with consensys/live-libs

### ISSUE THREAD

**Issue by axic** [ethereum/browser-solidity#163]
Maybe it would make sense supporting integration with https://github.com/ConsenSys/live-libs?

What do you think, @redsquirrel?

**Comment by redsquirrel** [comment]
😄  That is exactly the reason I got involved with browser-solidity in the first place. 😄 

Let's make it happen!

**Comment by chriseth** [comment]
@redsquirrel can you provide a short description of what it exactly is, what the itegration would be and if you would need features from the compiler?

**Comment by redsquirrel** [comment]
Fundamentally, Live Libs is a [smart contract](https://github.com/ConsenSys/live-libs/blob/master/contracts/LiveLibs.sol). That contract stores a registry of libraries that are live on the blockchain. Each library has a name (bytes32) and version, along with its address, ABI, author address, and an optional set of "resources" to store URLs to the source code, documentation, etc.

With the data in the Live Libs registry, it's possible to compile against and use live libraries rather than copying code into your project and having to pay for its deployment. With the library's ABI, it's possible to generate the source code for the abstract interface, and feed that to the compiler at compile time.

For example, assuming there's a `Math` library at address `0xabcd1234`, with an interface of:

```
library Math {
    function add(int a, int b) returns (int);
}
```
If this is stored in Live Libs, then, given some integration work, it's possible to write a contract like:

```
import "Math-0.1.5";
contract Foo {
    function bar() returns (int) {
        return Math.add(5, 3);
    }
}
```
The integration happens on the `import`. And `"Math-0.1.5"` could be `"live-libs::Math-0.1.5"` if we wanted it to be more self-documenting.

The browser-solidity integration would use the JavaScript interface to Live Libs, and would need to intercept the missing import, look up the contract, and feed the abstract source to the compiler, as well as a UI component to give developers insight into which libraries are available on the Ethereum network they're connected to.

**Comment by axic** [comment]
@redsquirrel all of that should be pretty doable since we have import callback.

I think the best would be having the ability to subscribe to the import queue on `compiler` and the separate live-libs integration could subscribe to that.

**Comment by axic** [comment]
Probably we should also think how to include versioning information in there? I like what npm does with `^a.b.c`.

Not fully sure this all belongs to the import statement.

**Comment by redsquirrel** [comment]
I should have also mentioned that the integration requires the library address to be linked to the contract's bytecode. So the address (`0xabcd1234` in my example) needs to be provided to whatever is responsible for linking.

I actually hacked together a PoC a while back, but then realized that the browser-solidity source code was too monolithic to be extensible. Hence the efforts to refactor it. 😄 To complete the integration, I believe more refactoring (especially [universal-dapp](https://github.com/ethereum/browser-solidity/blob/master/src/universal-dapp.js)) might be necessary.

@axic Regarding where to indicate versioning information, I agree it feels a little odd to append it to the import statement, but where else would it go?

**Comment by axic** [comment]
@redsquirrel a different approach others are taking/can take is to have a dependencies file and let a tool outside download and install all the prerequisites. Such as `packages.json`.

**Comment by redsquirrel** [comment]
@axic Yep, that approach makes sense if you need to download and install stuff. But with Live Libs, there's nothing to download.

**Comment by axic** [comment]
@redsquirrel well, there is: the interface

**Comment by redsquirrel** [comment]
@axic No, the interface can be generated on-the-fly via the ABI that's stored in the registry. See https://github.com/ConsenSys/live-libs/blob/master/lib/generate.js

**Comment by axic** [comment]
@redsquirrel strictly speaking it has to download it from the blockchain first :eyes: :smiley:

**Comment by redsquirrel** [comment]
@axic True. But back to your point regarding a dependencies file: I think it only makes sense when you're downloading data/code/etc and storing it in your project.

**Comment by chriseth** [comment]
At the source code level, I would prefer to stick to only slashes for namespacing. The directory remappings are now flexible enough to configure dependencies on a per-file basis, similar to what npm does for packages. So we can use

`import "live-libs/lib/version"` for an exact import or `import live-libs/lib` for an import that is configured outside of the source file in a package file or even `import "live-libs/lib/^1.0.0` that resolves to some version compatible with `^1.0.0`.

I see some drawbacks here:

 1. you need a live connection to the blockchain to resolve the needed information
 2. you cannot use internal functions of libraries or libraries that operator on structs

but this should not hinder us from integrating, of course.

**Comment by axic** [comment]
I think it the import statement could really benefit from being URL based:
- `live-libs://<lib>/<version>`
- `bzz://<hash>` and `bzz://<hash>/<file>`
- `fs:///ipfs/<hash>` (the URL definition of IPFS)
- `mango://<hash or ENS name>/<file or commit hash>`
- `http://github.com/<user>/<repo>/<path>#<commit hash>`  (this is what npm supports)

**Comment by axic** [comment]
@redsquirrel but apart from naming in the import statement, did you had a chance looking at integration?

**Comment by redsquirrel** [comment]
@axic I haven't looked at integration. Recently I've switched my focus to upgrade-ability rather than reuse-ability. And so I've stopped working on Live Libs, because Solidity libraries are antithetical to upgradable contracts. (Due to being statically linked.) I could imagine getting back to reusability and Live Libs once I find a more comfortable approach using contracts and `delegatecall`.

**Comment by axic** [comment]
@redsquirrel are you still thinking to work on this project or should we close this issue?

**Comment by redsquirrel** [comment]
You can close the issue

**Comment by axic** [comment]
@redsquirrel sorry to hear that

**Comment by redsquirrel** [comment]
@axic In retrospect, Live Libs was a premature solution, and libraries probably weren't the best way to approach reuse. I'm interested to see where the [Ethereum Smart Contract Packaging Specification](https://github.com/ethereum/EIPs/issues/190) takes us.
