### ISSUE TITLE
Static Analysis: Warn about the usage of tx.origin

### ISSUE THREAD

**Issue by chriseth** [ethereum/browser-solidity#173]
There are not a lot of uses of `tx.origin`, so we should add a warning to make the average developer aware that this is probably not what they want and they should not use `tx.origin` for authentication purposes.

**Comment by D-Nice** [comment]
I disagree with removing it, but having warnings is a good idea, early on I contemplated on using tx.origin to avoid the stub wallet issues some people were running into, where they couldn't receive funds, due to their fallback function requiring more gas than send provides.

Is it ever acceptable for contracts to implement tx.origin to specifically avoid ever being called by other contracts? I believe one could make a if msg.sender != tx.origin modifier for external functions to check for that?

**Comment by PeterBorah** [comment]
> Is it ever acceptable for contracts to implement tx.origin to specifically avoid ever being called by other contracts? I believe one could make a if msg.sender != tx.origin modifier for external functions to check for that?

We discussed this question in the [other issue](https://github.com/ethereum/solidity/issues/683#issuecomment-234079050). My position is that such a modifier does more harm than good (by breaking things like multisig wallets), and probably won't work after EIP 101.

**Comment by axic** [comment]
I think we should have this as a warning in the compiler and not in browser-solidity.

**Comment by axic** [comment]
Fixed by #298.
