### ISSUE TITLE
Move file tabs to list view on the left

### ISSUE THREAD

**Issue by chriseth** [ethereum/browser-solidity#251]
Open files should not be displayed as tabs but rather as a list of files on the left, as popular in various other IDEs. This list should be collapsible and it should also be possible to convert it to a directory view in the future to prepare for https://github.com/ethereum/browser-solidity/issues/42

**Comment by ramkarolis** [comment]
Hi Chriseth, I will have a look at this issue today and see what I can do. Would it perhaps be desirable to be able to have it both ways though, depending on user's preferences?

**Comment by chriseth** [comment]
@ramkarolis thanks a lot for looking into this! If you prefer real-time communication, please use http://gitter.im/ethereum/solidity

Concerning your question: Yes, there might be value in using a button to toggle from "tabs" to "list view", but I'm not sure how well that scales with the "directory" way to do it later. Perhaps we could just provide the full path in the tab.

In any case, please also add a toggle button for the "list view" so that it can be hidden if needed.

**Comment by ramkarolis** [comment]
@chriseth I have joined the channel, thanks! Here is the initial prototype https://github.com/ramkarolis/browser-solidity. Currently, it just lists the files on the left rather than tabs. I will showcase a way of how they would look in the directories tomorrow.

Now a couple questions/suggestions:
1. It might be good to make the editor, files list and pane on the right variable width which can be adjusted with drag & drop. Perhaps that can be handled as a separate issue.
2. Are there general design guidelines on how the output should look like? It might be helpful to have at least approximate design of what we are striving to achieve.

Happy to contribute and very excited about the future of Ethereum! :)

**Comment by chriseth** [comment]
@ramkarolis that's great news, thanks! Unfortunately, I won't be available myself in the next days, but @axic and @yann300 can help you. I think it is good to keep the first change limited and add a way to change the width later (we already have that for the right hand pane, perhaps some code can be shared there - please don't hesitate to refactor).

We don't have design guidelines, and actually this is something we would like to change in the near future - so we are looking for a ui designer to take a look.

**Comment by axic** [comment]
Based on the meeting today, we're going to:
- have a tree view of available files (including read-only imported files)
- and a list of "last accessed files" in order of last access

**Comment by ramkarolis** [comment]
Hi guys, my apologies I left this off without a wood. I had a go at it but changes were larger than expected and other urgent matters took over. I won't be contributing to this particular issue at least for now, hope you understand. All the best!

**Comment by chriseth** [comment]
@ramkarolis thanks for the notice and no worries!

**Comment by axic** [comment]
No worries @ramkarolis, check back later when you have time, there might be some other small tasks for taking 😉
