### ISSUE TITLE
Value: "0x" Decoded: Failed to decode output: Error: Invalid offset: 0

### ISSUE THREAD

**Issue by hrishikeshio** [ethereum/browser-solidity#410]
Getting this error when trying to read a constant function using geth 1.5.8-stable.
No issues when using geth 1.5.4-stable.
Running on private network
geth --maxpeers 0 --nodiscover --gasprice 0 --gpomin 0 --gpomax 0 --rpc --rpccorsdomain "*" --rpcaddr 0.0.0.0 --mine --password pass  --unlock 0 console

**Comment by hrishikeshio** [comment]
Complete report http://pastebin.com/SaLZbnRP

**Comment by yann300** [comment]
could you try to add the options `rpcapi`
`--rpcapi web3,eth,debug,net`

**Comment by hrishikeshio** [comment]
Made no difference

**Comment by yann300** [comment]
seems to be a bug in geth
https://github.com/ethereum/go-ethereum/issues/3653

**Comment by bas-vk** [comment]
It turns out this is by design.

The `eth_estimate` method that is used to get a gas estimate for the transaction accepts an optional gas limit. Browser solidity does not specify this value. In that case geth uses the pending block gas limit as an upper bound. Therefore the returned value can never be larger than the current pending block gas limit. If the transaction requires more gas than this upper bound the transaction will fail. I believe that is what happened here. Basically the contract was not deployed and the constant function was called on an non-existing contract.

Parity uses a different approach and uses an hard coded upper bound of 1_000_000_000_000u64. If you want this behaviour you can set a custom upper bound with the `gas` property.

**Comment by axic** [comment]
@bas-vk do you know by any chance if Parity ignores that gas parameter if supplied? Or would it fail?

**Comment by bas-vk** [comment]
I *think* parity ignores it.
https://github.com/ethcore/parity/blob/master/ethcore/src/client/client.rs#L911

From what I understand of it parity first tries to execute the transaction with the current block gas limit. If that fails it retries it with the hard coded upper bound. If the transaction is executed successfully it has established a valid upper bound and than tries to make a better estimate through a binary search.

**Comment by yann300** [comment]
ok I see, and this new optional parameter has been added recently? cause everything worked with geth 1.5.4 .
seems @karalabe found out that this is because of the `--dev` param . I can't check that now  but I could so some more check on Monday

**Comment by karalabe** [comment]
@bas-vk The issue you describe happens for a new chain with a limited initial block size. Although it's a good question whether we want to handle this scenario, the original problem was caused by pre-homestead contract creations not throwing (using all gas) upon failure.

https://github.com/ethereum/go-ethereum/issues/3653#issuecomment-278727050
