### ISSUE TITLE
Development console

### ISSUE THREAD

**Issue by chriseth** [ethereum/browser-solidity#445]
We should either expose contract objects to the global namespace ( #402 ) or provide a custom development console. Perhaps the latter is easier to understand and use for users. The idea would be to have an html element that behaves much like a browser's development console. I'm not sure yet how to best incorporate that, but we had something similar in mix.

**Comment by yann300** [comment]
We had the dev console in mix because mix also provided the frontend integration which remix does not have. so I am not sure we should have a dev console as mix or chromium have.
The mix dev console was very tiny...
I would maybe have a large input area in remix where user can paste a script (that deploy/call contracts). In that way we could also at the same time have something that looks like the "scenario" feature we had in mix.
Also when a bunch of transactions are displayed in remix we could have a button like "Save scenario" that will output and save the corresponding script.
