### ISSUE TITLE
Compilation Issue

### ISSUE THREAD

**Issue by mudlee** [ethereum/browser-solidity#615]
When I compile solidity file using remix's different versions (0.4.11 and 0.4.13), the binary is also not the same. Hence, I don't know which one is the correct. Also, if I use the latest solc binary for linux with the same options, I get a third version of binary.
Is that normal?

I found nothing about the details of the compilation and this is a little bit annoying.

**Comment by axic** [comment]
The difference between the output of a Linux and a Emscripten ("remix") binary is most likely due to a difference in the metadata (see http://solidity.readthedocs.io/en/develop/miscellaneous.html#contract-metadata). Different compiler versions will very likely output different code due to changes, improvements and fixes.

Please open an issue on https://github.com/ethereum/solidity if the above doesn't answer your question.

**Comment by mudlee** [comment]
thx. will check soon
