### ISSUE TITLE
Extract static analysis component into npm module

### ISSUE THREAD

**Issue by chriseth** [ethereum/browser-solidity#888]
The static analysis modules should be usable as part of a CI run. Because of that, they should have their own npm module and should work without any UI dependencies.

A quick look at the code showed that `yo-yo` is used, but it should be easy to remove that. Furthemore, some utility functions are used which are probably also quite easy to replace.

**Comment by androlo** [comment]
Noticed AST walking was one of those utilities, which has only a couple of functions in it.

I have also noticed that the current format is generated using something called legacy mode in the json converter. This only seem to supports legacy mode.

**Comment by yann300** [comment]
hmm yes depending on the remix repo only because of the ast walker is too much :)
well I think we should start to split up the remix repo first... (or just keep the remix dependency for now).

for the `yo-yo` dependency, we use it to avoid script injection  ( `warning` is html formatted ) . but that totally fine to use another structure for `warning` (like a json which describe the warning).

**Comment by yann300** [comment]
I could start to split up the remix repo when I get some time
